---
apiVersion: operators.coreos.com/v1
kind: Operator
metadata:
  name: nmstate-operator.openshift-nmstate-operator
  annotations:
    ran.openshift.io/ztp-deploy-wave: "2"
status:
  components:
    refs:
      - kind: Subscription
        namespace: openshift-nmstate-operator
        conditions:
          - type: CatalogSourcesUnhealthy
            status: "False"
      - kind: InstallPlan
        namespace: openshift-nmstate-operator
        conditions:
          - type: Installed
            status: "True"
      - kind: ClusterServiceVersion
        namespace: openshift-nmstate-operator
        conditions:
          - type: Succeeded
            status: "True"
            reason: InstallSucceeded
