---
apiVersion: ran.openshift.io/v1
kind: PolicyGenTemplate
metadata:
  name: "htworker"
  namespace: "ztp-group"
spec:
  bindingRules:
    htworker: ""
  remediationAction: inform
  mcp: "worker"
  sourceFiles:
    - fileName: PerformanceProfile.yaml
      policyName: "config-nodes"
      metadata:
        name: performance-ht100gb
        annotations:
          kubeletconfig.experimental: |
            {"allowedUnsafeSysctls":["net.core.somaxconn","kernel.msg*"],"systemReserved":{"memory": "300Mi"},"kubeReserved":{"memory": "768Mi"}}
      spec:
        additionalKernelArgs:
          - "nohz_full=4-15"
        cpu:
          isolated: "4-15"
          reserved: "0-3"
        hugepages:
          defaultHugepagesSize: 1G
          pages:
            - size: 1G
              count: 4
        nodeSelector:
          node-role.kubernetes.io/ht100gb: ""
        numa:
          topologyPolicy: single-numa-node
        workloadHints:
          realTime: false
          highPowerConsumption: false
          perPodPowerManagement: false
        realTimeKernel:
          enabled: false
    # https://github.com/openshift-kni/cnf-features-deploy/blob/efe8c5ddcad32b5d0b8c58f51d391aafc96fe77d/ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-sno-ranGen.yaml#L124-L140
    # https://github.com/openshift-kni/cnf-features-deploy/blob/efe8c5ddcad32b5d0b8c58f51d391aafc96fe77d/ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-sno-ranGen.yaml#L196-L221
