---
apiVersion: ran.openshift.io/v1
kind: PolicyGenTemplate
metadata:
  name: "metallb"
  namespace: "ztp-group"
spec:
  bindingRules:
    sites: "n95"
  remediationAction: inform
  sourceFiles:
    - fileName: metallb/bfdProfile.yaml
      policyName: "config-metallb"
    - fileName: metallb/bgpPeer.yaml
      policyName: "config-metallb"
    - fileName: metallb/community.yaml
      policyName: "config-metallb"
    - fileName: metallb/ipAddressPool.yaml
      policyName: "config-metallb"
    - fileName: metallb/bgpAdvertisement.yaml
      policyName: "config-metallb"
