---
name: ztp-e2e
on:  # yamllint disable-line rule:truthy
  workflow_dispatch:
jobs:
  stage0:
    name: Setup Virtual Infra
    runs-on: [self-hosted]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Clean Virtual Infra
        run: |
          ./sinfra --clean -auto-timeout 0s --continue-on-error
      - name: Setup Virtual Infra
        run: |
          echo '${{ secrets.PULL_SECRET }}' > .pull-secret.json
          echo '${{ secrets.ARGO_GIT_KEY }}' > .github-argo
          echo '${{ secrets.BMH_SECRET }}' > bmh-secret.yaml
          ./sinfra --setupInfra -auto-timeout 0s
          podman logs workstation
  stage1:
    name: Deploy SNO Cluster
    runs-on: [self-hosted]
    needs: [stage0]
    if: needs.stage0.result == 'success'
    steps:
      - name: Deploy SNO using agent-based
        run: |
          COMMANDS=$(cat <<EOF
            ./deploy-ocp.sh hub
            export KUBECONFIG=/share/hub/auth/kubeconfig
            openshift-install agent wait-for install-complete --log-level info --dir /share/hub
          EOF
          )
          podman exec -it workstation  bash -c "$COMMANDS"
          echo "wget http://10.0.0.1:9000/hub/auth/kubeconfig -O ~/.kube/hub.yaml"
          echo "curl -s http://10.0.0.1:9000/hub/auth/kubeadmin-\password | xsel --input --clipboard"
      - name: Provision SNO to be ACM/ZTPHub
        run: |
          COMMANDS=$(cat <<EOF
            cd ./hub-template/day1
            ./install-acm.sh
            GITKEY_FILE=/workdir/.github-argo ./git-ssh-access.sh
            PULL_SECRET_PATH=/workdir/.pull-secret.json ./install-ztp.sh
          EOF
          )
          podman exec -it workstation  bash -c "$COMMANDS"
  stage2:
    name: Wait SPOKE
    runs-on: [self-hosted]
    needs: [stage0, stage1]
    if: needs.stage1.result == 'success'
    steps:
      - name: Wait SPOKE
        run: |
          COMMANDS=$(cat <<EOF
            oc apply -f bmh-secret.yaml
            oc apply -k github.com/karampok/autosecret/config/default
            echo "https://openshift-gitops-server-openshift-gitops.apps.hub.eric.vlab/"
            timeout 1200 ./bin/watch-ztp 5gc || echo ""
            oc -n 5gc wait clusterdeployment 5gc --for=condition=Provisioned --timeout=5400s
            timeout 540 oc -n 5gc get policies -w || echo ""
            oc -n ztp-install wait cgu 5gc --for=condition=Succeeded --timeout=2500s
          EOF
          )
          podman exec -it workstation  bash -c "$COMMANDS"
