---
apiVersion: metallb.io/v1beta1
kind: BGPAdvertisement
metadata:
  name: green
  namespace: metallb-system
  annotations:
    ran.openshift.io/ztp-deploy-wave: "2"
spec:
  communities:
    - greenc
  ipAddressPools:
    - greenips
  peers:
    - greenpeers
