---
apiVersion: metallb.io/v1beta1
kind: BGPPeer
metadata:
  name: greenpeers
  namespace: metallb-system
  annotations:
    ran.openshift.io/ztp-deploy-wave: "3"
spec:
  peerAddress: 11.11.11.254
  peerASN: 8002
  myASN: 7003
  holdTime: "180s"
  bfdProfile: bfd-profile
  nodeSelectors:
    - matchExpressions:
      - key: kubernetes.io/hostname
        operator: In
        values: [5gc-m2]
