---
apiVersion: metallb.io/v1beta1
kind: Community
metadata:
  name: greenc
  namespace: metallb-system
  annotations:
    ran.openshift.io/ztp-deploy-wave: "2"
spec:
  communities:
    - name: greenc
      value: '7003:008'
